### ISSUE TITLE
issue while running evaluate.py

### ISSUE THREAD

**Issue by rohitupreti** [SlapBot/drone-detection#29]
2023-02-17 13:47:43.161332: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-17 13:47:44.027961: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-02-17 13:47:44.028084: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
2023-02-17 13:47:44.028105: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
/content/drone-detection/Trained-Model/drone-detection-v5.h5
2023-02-17 13:47:49.313845: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
WARNING:tensorflow:From /usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/pyct/static_analysis/liveness.py:83: Analyzer.lamba_check (from tensorflow.python.autograph.pyct.static_analysis.liveness) is deprecated and will be removed after 2023-09-23.
Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089
WARNING:tensorflow:From /usr/local/lib/python3.8/dist-packages/tensorflow/python/autograph/pyct/static_analysis/liveness.py:83: Analyzer.lamba_check (from tensorflow.python.autograph.pyct.static_analysis.liveness) is deprecated and will be removed after 2023-09-23.
Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
Traceback (most recent call last):
  File "evaluate.py", line 14, in <module>
    boxes, scores, labels = c.predict_with_graph_loaded_model(processed_image, scale)
  File "/content/drone-detection/core.py", line 59, in predict_with_graph_loaded_model
    return self.predict(self.model, image, scale)
  File "/content/drone-detection/core.py", line 52, in predict
    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 2567, in predict_on_batch
    iterator = data_adapter.single_batch_iterator(
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/data_adapter.py", line 1833, in single_batch_iterator
    return iter(dataset)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 501, in __iter__
    raise RuntimeError("`tf.data.Dataset` only supports Python-style "
RuntimeError: `tf.data.Dataset` only supports Python-style iteration in eager mode or within tf.function.

using python3.8.10

**Comment by Karthik-Pippalla** [comment]
i have the same problems, please solve it
